#cloud-config
#Get Qwen3 Coder Next running.
runcmd:
  - |
    echo "Starting vLLM Docker container..."
    docker run -d \
      --name vllm \
      --network=host \
      --group-add=video \
      --ipc=host \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --privileged \
      --device /dev/kfd \
      --device /dev/dri \
      --restart=always \
      vllm/vllm-openai-rocm:v0.15.0-base \
      vllm serve Qwen/Qwen3-Coder-Next \
        --max-model-len 32768 \
        --block-size 512 \
        --enable-auto-tool-choice \
        --tool-call-parser qwen3_coder
