#cloud-config
#Get Qwen3 Coder Next running.
runcmd:
  - |
    echo "Starting vLLM Docker container..."
    docker rm -f vllm || true
    docker run -d \
      --name vllm \
      --network=host \
      --group-add=video \
      --ipc=host \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --privileged \
      --device /dev/kfd \
      --device /dev/dri \
      --restart=always \
      rocm/vllm:latest \
      vllm serve Qwen/Qwen3-Coder-Next \
        --max-model-len 32768 \
        --block-size 256 \
        --enable-auto-tool-choice \
        --tool-call-parser hermes
  - |
    echo "vLLM container started. Check status with: docker logs -f vllm"
    echo "API should be available on port 8000 (host networking)."
