#cloud-config
# Simple cloud-init to run vLLM Docker container with tool calling enabled
# This will start the vLLM service automatically on first boot
runcmd:
  - |
    echo "Starting vLLM Docker container with tool calling support..."
    docker run -d \
      --name vllm \
      --network=host \
      --group-add=video \
      --ipc=host \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --privileged \
      --device /dev/kfd \
      --device /dev/dri \
      --restart=always \
      rocm/vllm:latest \
      vllm serve Qwen/Qwen2-7B-Instruct \
        --enable-auto-tool-choice \
        --tool-call-parser hermes
  - |
    echo "vLLM container started with tool calling enabled."
    echo "Check status with: docker logs vllm"
    echo "vLLM should be available shortly on port 8000. GPU access and networking are configured for host mode."
    echo "Tool calling (auto) is now supported for clients like OpenCode."