#cloud-config
# Get Qwen/Qwen3.5-35B-A3B Running
runcmd:
  - |
    echo "Starting vLLM Docker container..."
    docker rm -f vllm || true
    mkdir -p /opt/hf
    docker run -d \
      --name vllm \
      --network=host \
      --group-add=video \
      --ipc=host \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --device /dev/kfd \
      --device /dev/dri \
      --restart=always \
      -v /opt/hf:/root/.cache/huggingface \
      rocm/vllm:latest \
      vllm serve Qwen/Qwen3.5-35B-A3B \
        --trust-remote-code \
        --dtype bfloat16 \
        --gpu-memory-utilization 0.90 \
        --max-model-len 65536 \
        --block-size 256 \
        --enable-auto-tool-choice \
        --tool-call-parser qwen3_xml
  - |
    echo "vLLM container started. Check status with: docker logs -f vllm"
    echo "API should be available on port 8000 (host networking)."