#cloud-config
# Run Qwen2.5-Coder-32B-Instruct on vLLM (ROCm)

runcmd:
  - |
    echo "[cloud-init] Starting vLLM (Qwen2.5-Coder-32B-Instruct)..."

    IMAGE="rocm/vllm:v0.14.0_amd_dev"
    NAME="vllm"
    MODEL="Qwen/Qwen2.5-Coder-32B-Instruct"

    # Pull image
    docker pull "${IMAGE}"

    # Remove any existing container
    docker rm -f "${NAME}" 2>/dev/null || true

    # Run vLLM
    docker run -d \
      --name "${NAME}" \
      --network=host \
      --ipc=host \
      --group-add=video \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --privileged \
      --device /dev/kfd \
      --device /dev/dri \
      --restart=always \
      -e VLLM_ROCM_USE_AITER=1 \
      -e VLLM_ROCM_USE_AITER_UNIFIED_ATTENTION=1 \
      "${IMAGE}" \
      vllm serve "${MODEL}" \
        --max-model-len 32768 \
        --block-size 256 \
        --attention-backend ROCM_AITER_UNIFIED_ATTN

    echo "[cloud-init] vLLM launched. Check logs with: docker logs -f vllm"