#cloud-config
# Get Qwen/Qwen3.5-35B-A3B Running
runcmd:
  - |
    echo "Starting vLLM Docker container..."
    docker rm -f vllm || true
    mkdir -p /opt/hf
    docker run -d \
      --name vllm \
      --network=host \
      --group-add=video \
      --ipc=host \
      --cap-add=SYS_PTRACE \
      --security-opt seccomp=unconfined \
      --privileged \
      --device /dev/kfd \
      --device /dev/dri \
      -v /opt/hf:/root/.cache/huggingface/transformers \
      --restart=always \
      rocm/vllm-dev:nightly \
      vllm serve Qwen/Qwen3.5-35B-A3B \
        --max-model-len 131272 \
        --block-size 256 \
  - |
    echo "vLLM container started. Check status with: docker logs -f vllm"
    echo "API should be available on port 8000 (host networking)."


    